name: Xbox Guitar Stock

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install requests
      run: |
        pip install requests

    - name: Install bs4
      run: |
        pip install beautifulsoup4
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
        
    - name: Check Stock
      run: |
        python -c "import requests, http.client, urllib
        from bs4 import BeautifulSoup

        url = 'https://pdp.com/products/xbox-series-x-s-xbox-one-pc-riffmaster-wireless-guitar-controller'
        response = requests.get(url)

        soup = BeautifulSoup(response.content, 'html.parser')

        stock = soup.find('div', class_='js-pdp-add-to-cart').text.strip().lower()

        if stock == 'add to cart':
            conn = http.client.HTTPSConnection('api.pushover.net:443')
            conn.request(
                'POST',
                '/1/messages.json',
                urllib.parse.urlencode(
                    {
                        'token': os.environ['APP_TOKEN'],
                        'user': os.environ['USER_TOKEN'],
                        'message': 'THE GUITAR IS IN STOCK! https://pdp.com/products/xbox-series-x-s-xbox-one-pc-riffmaster-wireless-guitar-controller',
                    }
                ),
                {'Content-type': 'application/x-www-form-urlencoded'},
            )
            conn.getresponse()"
